# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  # Exercise: Config and Deployment
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
              # You can get this ID in the section where you registered the SSH Key
              fingerprints: [79:26:76:1a:35:4e:8d:be:26:e5:44:73:4d:44:86:40] 
      - run:
          name: Install Ansible
          command: |
            # Install Ansible
            apk add --update ansible
      - run:
          name: List files
          command: |
            ls -al
            echo '^^^The files in my repo^^^'
      - run:
          name: Run Playbook and Configure server
          command: |
            # Your command
            ansible-playbook -i inventory main.yml #--private-key "udacity.pem"
workflows:
  myWorkflow:
    jobs:
      - configure_infrastructure
